#!/usr/bin/env bash
# stage-5-sds-update.sh — Stage 5: Tech Lead SDS Update.
# Updates documents/design.md, generates 04a-sds-diff.md audit trail.
# See: requirements.md FR-6, FR-8, FR-10, FR-14.
#
# Usage: stage-5-sds-update.sh <issue-number>
#
# When sourced with --source-only, only defines functions (for testing).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=lib.sh disable=SC1091
source "$SCRIPT_DIR/lib.sh"

STAGE_NAME="stage-5-sds-update"
AGENT_PROMPT="$REPO_ROOT/.sdlc/agents/tech-lead-sds.md"

# ============================================================
# validate_sds_updated()
# Checks that design.md has been modified (git diff non-empty).
# Usage: validate_sds_updated
# Returns: 0 if modified, 1 if no changes.
# ============================================================
validate_sds_updated() {
  local diff_output
  diff_output=$(git -C "$REPO_ROOT" diff -- documents/design.md)

  if [[ -z "$diff_output" ]]; then
    log ERROR "documents/design.md was not modified"
    return 1
  fi

  log INFO "SDS modification detected"
  return 0
}

# ============================================================
# validate_sds_components()
# Checks that new components have purpose, interfaces, deps.
# Usage: validate_sds_components <path>
# Returns: 0 if valid, 1 otherwise.
# ============================================================
validate_sds_components() {
  local path="$1"

  if [[ ! -s "$path" ]]; then
    log ERROR "SDS file is empty or missing: ${path}"
    return 1
  fi

  # Basic structure check: must have components section
  if ! grep -qi '## .*[Cc]omponents\|### .*[Cc]omp' "$path"; then
    log ERROR "SDS missing components section: ${path}"
    return 1
  fi

  log INFO "SDS components validated: ${path}"
  return 0
}

# ============================================================
# generate_sds_diff()
# Generates 04a-sds-diff.md from git diff of design.md.
# Usage: generate_sds_diff <output-path>
# ============================================================
generate_sds_diff() {
  local output_path="$1"

  local diff_output
  diff_output=$(git -C "$REPO_ROOT" diff -- documents/design.md)

  {
    echo "# SDS Diff (Stage 5 Audit Trail)"
    echo ""
    echo "Generated by \`stage-5-sds-update.sh\`."
    echo ""
    echo '```diff'
    echo "$diff_output"
    echo '```'
  } > "$output_path"

  log INFO "SDS diff generated: ${output_path}"
}

# ============================================================
# build_task_prompt()
# ============================================================
build_task_prompt() {
  local issue_number="$1"
  local decision_path="$2"
  local revised_path="$3"

  cat <<EOF
Issue #${issue_number}

Decision artifact: ${decision_path}
Revised plan artifact: ${revised_path}

Instructions:
1. Read ${decision_path} (the Architect's decision from Stage 4).
2. Read ${revised_path} (the revised plan from Stage 3).
3. Read documents/design.md (current SDS).
4. Update documents/design.md:
   - Add/modify components for the selected variant.
   - Every new component must have: purpose, interfaces, dependencies.
   - Scope changes to the selected variant only.
   - Follow SDS format from documents/CLAUDE.md.
5. Do NOT create any other files. Do NOT write source code.
EOF
}

# ============================================================
# main()
# ============================================================
main() {
  local issue_number="${1:-}"

  if [[ -z "$issue_number" ]]; then
    log ERROR "Usage: stage-5-sds-update.sh <issue-number>"
    exit 1
  fi

  if ! [[ "$issue_number" =~ ^[0-9]+$ ]]; then
    log ERROR "Issue number must be numeric: ${issue_number}"
    exit 1
  fi

  local pipeline_dir="$REPO_ROOT/.sdlc/pipeline/${issue_number}"
  local decision_path="${pipeline_dir}/04-decision.md"
  local revised_path="${pipeline_dir}/03-revised-plan.md"
  local sds_diff_path="${pipeline_dir}/04a-sds-diff.md"
  local sds_path="$REPO_ROOT/documents/design.md"
  local log_dir="${pipeline_dir}/logs"
  local log_json="${log_dir}/${STAGE_NAME}.json"
  local allowed_paths=(
    "documents/design.md"
  )

  mkdir -p "$pipeline_dir" "$log_dir"

  log INFO "=== Stage 5: SDS Update — Issue #${issue_number} ==="

  if ! validate_artifact "$decision_path"; then
    log ERROR "Stage 4 artifact missing: ${decision_path}"
    report_status "$issue_number" "Stage 5 (SDS Update): FAILED — missing 04-decision.md"
    exit 1
  fi

  local task_prompt
  task_prompt=$(build_task_prompt "$issue_number" "$decision_path" "$revised_path")

  report_status "$issue_number" "Stage 5 (SDS Update): started"

  local output
  output=$(continuation_loop "$AGENT_PROMPT" "$task_prompt" "$sds_path")
  echo "$output" > "$log_json"

  # Post-agent validation
  local session_id
  session_id=$(echo "$output" | jq -r '.session_id // empty')
  local cont=0
  local max_cont="${SDLC_MAX_CONTINUATIONS}"

  while ! validate_sds_updated || ! validate_sds_components "$sds_path"; do
    if (( cont >= max_cont )); then
      log ERROR "Continuation limit reached: SDS validation failed"
      report_status "$issue_number" "Stage 5 (SDS Update): FAILED — validation failed after ${max_cont} continuations"
      exit 1
    fi

    (( cont++ ))
    local error_msg="documents/design.md must be modified with new components. Every component needs: purpose, interfaces, dependencies."

    log WARN "Continuation ${cont}/${max_cont}: ${error_msg}"
    output=$(retry_with_backoff claude \
      --resume "$session_id" \
      -p "Validation failed: ${error_msg} Fix the issues in documents/design.md." \
      --output-format json)
    echo "$output" > "$log_json"
  done

  if ! safety_check_diff "${allowed_paths[@]}"; then
    log ERROR "Safety check failed"
    report_status "$issue_number" "Stage 5 (SDS Update): FAILED — safety check failed"
    exit 1
  fi

  # Generate SDS diff audit trail (FR-6)
  generate_sds_diff "$sds_diff_path"

  if [[ -n "$session_id" ]]; then
    local jsonl_source
    jsonl_source=$(find "$HOME/.claude/projects/" -name "*.jsonl" -newer "$log_json" 2>/dev/null | head -1)
    if [[ -n "$jsonl_source" ]]; then
      cp "$jsonl_source" "${log_dir}/${STAGE_NAME}.jsonl"
    fi
  fi

  commit_artifacts \
    "sdlc(tech-lead-sds): ${issue_number} — SDS update" \
    "$sds_path" \
    "$sds_diff_path" \
    "$log_json"

  report_status "$issue_number" "Stage 5 (SDS Update): completed"
  log INFO "=== Stage 5: SDS Update — completed ==="
}

if [[ "${1:-}" != "--source-only" ]]; then
  main "$@"
fi
